[package]
name = "rustest"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
description.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
libtest-mimic = "0.8.1"
rustest-macro = { version = "0.0.2", path = "../rustest-macro" }

[[test]]
name = "test"
harness = false
